### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tangtszchun**

### CODE REVIEW

**Comment by DinethP** [comment]
@tangtszchun Are you adding a new SID to the readme file?

**Comment by 11551107C1** [comment]
seems yes?

**Comment by 3250TTTony** [comment]
nice!!!

**Comment by iPhoneL** [comment]
Not sure if this will cause issue since he is using old version master

**Comment by 11551107C1** [comment]
added 2 spaces after the line added, can see see if any problem exists

**Pull request merged**
