### PR TITLE
Spacing, spacing, spacing

### PR DESCRIPTION
**Pull request by iPhoneL**
forget spacing while resolve conflict

### CODE REVIEW

**Comment by 11551107C1** [comment]
heyyy guys, I found there are 13 files in _stu while only 12 of them were included. Also, only 10 of them were correctly included and could be seen in the website

**Comment by iPhoneL** [comment]
> heyyy guys, I found there are 13 files in _stu while only 12 of them were included. Also, only 10 of them were correctly included and could be seen in the website

strange

**Comment by 11551107C1** [comment]
veeeeeeery strange. so who have not included their file in our read me??????

or we finish this issue first?

hope everyone could see if their file are included and showed correctly then:(

**Comment by iPhoneL** [comment]
> veeeeeeery strange. so who have not included their file in our read me??????
> 
> or we finish this issue first?
> 
> hope everyone could see if their file are included and showed correctly then:(

I am checking what's going wrong

**Comment by 3250TTTony** [comment]
???????

**Comment by 11551107C1** [comment]
Dear Tony, your file is not correctly shown in the blog repo. could you see if you have created the file of included it correctly?

**Comment by iPhoneL** [comment]
> Dear Tony, your file is not correctly shown in the blog repo. could you see if you have created the file of included it correctly?
1155110364.md not exist, I think the correct one is 1155110464.md.

**Comment by 11551107C1** [comment]
> > Dear Tony, your file is not correctly shown in the blog repo. could you see if you have created the file of included it correctly?
> > 1155110364.md not exist, I think the correct one is 1155110464.md.

then lets change it la?

**Pull request merged**
