### PR TITLE
Update 1155115792.md

### PR DESCRIPTION
**Pull request by iPhoneL**
Just realize that is @my github name not my CSE acc name :rofl:

### CODE REVIEW

**Comment by 3250TTTony** [comment]
hmm?

**Comment by iPhoneL** [comment]
> hmm?

Tiny changes on my sid.md, you can help me to approve this changes.

**Comment by 3250TTTony** [comment]
I'd love to but how to approve..... not familiar with github........

**Comment by 3250TTTony** [comment]
nvm

**Comment by iPhoneL** [comment]
> nvm

Thx a lot.

**Pull request merged**
